//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoVar8SAA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentView
    {
        public string Title { get; set; }
        public Nullable<int> CountSale { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string Phone { get; set; }
        public string Expr1 { get; set; }
    }
}
